Repository YelShydenko/Garden-Products, pull requests merged in 2024-08, with the labels that each got.

#5 Kobets/footer
  public/images/ic-instagram.png
  public/images/ic-whatsapp.png
  src/Components/Footer/Footer.jsx
  src/Components/Footer/Footer.scss
Labels: documentation

#17 Filter and sort functionality
  src/Components/FilterAndSort/FilterAndSort.jsx
  src/Components/FilterAndSort/FilterAndSort.scss
  src/Components/SaleProductsMainPage/SaleProductsMainPage.jsx
  src/pages/CategoriesProduct/CategoriesProduct.jsx
  src/pages/Products/AllProducts.jsx
  src/pages/SaleProductsPage/SaleProductsPage.jsx
  src/pages/SaleProductsPage/SaleProductsPage.scss
  src/store/features/productSlice.js
Labels: enhancement

#18 refactoring and fixed style
  src/App.jsx
  src/Components/CategoriesMainPage/CategoriesMainPage.jsx
  src/Components/CategoriesMainPage/CategoriesMainPage.scss
  src/Components/CategoryCard/CategoryCard.jsx
  src/Components/FilterAndSort/FilterAndSort.jsx
  src/Components/FilterAndSort/FilterAndSort.scss
  src/Components/Footer/Footer.scss
  src/Components/Header/Header.jsx
  src/Components/Header/Header.scss
  src/Components/ProductCard/ProductCard.jsx
  src/Components/ProductCard/ProductCard.scss
  src/Components/SaleProductsMainPage/SaleProductsMainPage.jsx
  src/pages/CategoriesPage/CategoriesPage.jsx
  src/pages/CategoriesPage/CategoriesPage.scss
  src/pages/CategoriesProduct/CategoriesProduct.jsx
  src/pages/CategoriesProduct/CategoriesProduct.scss
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.scss
  src/pages/Products/AllProducts.jsx
  src/pages/Products/AllProducts.scss
  src/pages/SaleProductsPage/SaleProductsPage.jsx
  src/pages/SaleProductsPage/SaleProductsPage.scss
Labels: bugfix

#20 Cart page
  src/App.jsx
  src/Components/CartProductCard/CartProductCard.jsx
  src/Components/CartProductCard/CartProductCard.scss
  src/Components/OrderModalWindow/OrderModalWindow.jsx
  src/Components/OrderModalWindow/OrderModalWindow.scss
  src/Components/ProductCard/ProductCard.jsx
  src/Components/ProductCard/ProductCard.scss
  src/Components/SaleForm/SaleForm.scss
  src/Components/SectionDivider/SectionDivider.scss
  src/Components/UI/Input/Input.jsx
  src/Components/UI/Input/Input.scss
  src/assets/styles/variables.scss
  src/pages/Cart/Cart.jsx
  src/pages/Cart/Cart.scss
  src/store/features/productSlice.js
Labels: enhancement

#28 created breadcrumbs
  src/Components/Breadcrumbs/Breadcrumbs.jsx
  src/Components/Breadcrumbs/Breadcrumbs.scss
  src/Components/UI/Button/Button.jsx
  src/Components/UI/Button/Button.scss
  src/pages/CategoriesPage/CategoriesPage.jsx
  src/pages/CategoriesPage/CategoriesPage.scss
  src/pages/CategoriesProduct/CategoriesProduct.jsx
  src/pages/FavoritesPage/FavoritesPage.jsx
  src/pages/ProductPage/ProductPage.jsx
  src/pages/ProductPage/ProductPage.scss
  src/pages/Products/AllProducts.jsx
  src/pages/SaleProductsPage/SaleProductsPage.jsx
  src/pages/SaleProductsPage/SaleProductsPage.scss
Labels: enhancement
